# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpHRh6ZppogJteLMB79p0QbFDPlxZC1k
"""

import numpy as np
import pandas as pd
from google.colab import files
files.upload()

import numpy as np
blo = pd.read_csv('blosum62.csv')
seq1 = "MNALQM"
seq2 = "NALMSQA"
gap_score = -6
#seq1 = input("Sequence 1: ")
#seq2 = input("Sequence 2: ")
#blo=pd.read_CSV('blosum62.csv')

rows, columns = len(seq2)+1, len(seq1)+1
table = np.zeros((rows, columns), int)

table

blo

for i in range (1,rows):
  for j in range (1,columns):
    table[i][j]=blo[seq1[j-1]][seq2[i-1]]

table

for i in range(rows):
    table[i][0] = i*gap_score

for j in range(columns):
    table[0][j] = j*gap_score

for i in range(1, rows):
    for j in range(1, columns):
        diagonal = table[i-1][j-1] + blo[seq1[j-1]][seq2[i-1]]
        atas = table[i][j-1] + gap_score
        kiri = table[i-1][j] + gap_score
        table[i][j] = max(diagonal, atas, kiri)

print(table)

simpenan = np.zeros(shape=(rows,columns), dtype=np.int)

for i in range(1, rows):
    for j in range(1, columns):
        diagonal = table[i-1][j-1] + blo[seq1[j-1]][seq2[i-1]]
        atas = table[i][j-1] + gap_score
        kiri = table[i-1][j] + gap_score
        table[i][j] = max(diagonal, atas, kiri)
        
        if table[i][j]==diagonal:
          simpenan[i][j]=1
        elif table[i][j]==atas:
          simpenan[i][j]=2
        elif table[i][j]==kiri:
          simpenan[i][j]=3

simpenan

protein_1 =""
protein_2=""
skor=0
i=columns-1
j=rows-1    
while i>=0 and j>=0:
    
      
    if simpenan[j][i] == 1:
        protein_1 = seq1[i-1] + protein_1
        protein_2 = seq2[j-1] + protein_2
        i -= 1
        j -= 1
        


    elif simpenan[j][i] == 2:
        i=i-1
        protein_1 = seq1[i-1] + protein_1
        protein_2 = '-' + protein_2
      

        
    elif simpenan[j][i] == 3:
        protein_1 = '-' + protein_1
        protein_2 = seq2[j-1] + protein_2
        j=j-1
    

    else:break
    
    if simpenan[1][2] ==1:
          protein_1 = seq1[1] + protein_1
          protein_2 = '-' + protein_2

protein_1

protein_2